# Use an official OpenJDK image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the Java files into the image
COPY KeyValueStoreInterface.java KeyValueStoreServer.java /app/

# Compile the Java files
RUN javac KeyValueStoreInterface.java KeyValueStoreServer.java

# Set the command to run the server
CMD ["java", "KeyValueStoreServer"]
