version: "3.8"
services:
  kv_server_1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=5010
      - NODE_ID=1
      - PEERS=kv_server_2:5011,kv_server_3:5012
    networks:
      - kv_network
  kv_server_2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=5011
      - NODE_ID=2
      - PEERS=kv_server_1:5010,kv_server_3:5012
    networks:
      - kv_network
  kv_server_3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=5012
      - NODE_ID=3
      - PEERS=kv_server_1:5010,kv_server_2:5011
    networks:
      - kv_network
networks:
  kv_network:
    driver: bridge
