# Use an official OpenJDK image
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the Java files into the image
COPY KeyValueStoreInterface.java KeyValueStoreClient.java /app/

# Compile the Java files
RUN javac KeyValueStoreInterface.java KeyValueStoreClient.java

# Set the command to run the client
CMD ["java", "KeyValueStoreClient", "kv_server_1", "5010"]
